export enum EnvironmentsEnum {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  YOUTUBE_API_URL = 'YOUTUBE_API_URL',
  YOUTUBE_API_KEY = 'YOUTUBE_API_KEY',
  YOUTUBE_API_CHANNEL_ID = 'YOUTUBE_API_CHANNEL_ID',
}
